apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /admin/
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: hand2hand-config
          env:
            - name: DJANGO_SUPERUSER_NAME
              value: {{ .Values.backend.superuser.name }}
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hand2hand-secret
                  key: DJANGO_SUPERUSER_PASSWORD
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hand2hand-secret
                  key: DB_PASSWORD
            - name: DEEPL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hand2hand-secret
                  key: DEEPL_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
