apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DJANGO_SUPERUSER_NAME
              value: {{ .Values.backend.superuser.name }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.backend.superuser.password }}
            - name: DEBUG
              value: "False"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: {{ .Values.mysql.database }}
            - name: DB_USER
              value: {{ .Values.mysql.user }}
            - name: DB_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: DEEPL_API_KEY
              value: {{ .Values.backend.deeplApiKey }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
