apiVersion: v1
kind: ConfigMap
metadata:
  name: hand2hand-config
data:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  DEBUG: "False"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "{{ .Values.mysql.database }}"
  DB_USER: "{{ .Values.mysql.user }}"
  NODE_ENV: "production"
  VITE_API_BASE_URL: "http://135.237.53.26/api" 