apiVersion: v1
kind: Secret
metadata:
  name: hand2hand-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.mysql.password | b64enc }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.backend.superuser.password | b64enc }}
  DEEPL_API_KEY: {{ .Values.backend.deeplApiKey | b64enc }} 