# Generated by Django 5.2 on 2025-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='translated_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
