# Generated by Django 5.2 on 2025-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatmessage_translated_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
