# Generated by Django 5.2 on 2025-06-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('category_ids', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('transport_mode', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('reviews', models.JSONField(default=list)),
                ('deliveries_completed', models.IntegerField(default=0)),
                ('identity_img_url', models.URLField(blank=True, null=True)),
                ('day_of_week', models.JSONField(default=list)),
                ('time_slot', models.JSONField(default=list)),
                ('joined_date', models.DateField()),
                ('approval_status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Delivery Agent',
                'verbose_name_plural': 'Delivery Agents',
                'db_table': 'delivery_agents',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_rating', models.IntegerField(blank=True, null=True)),
                ('delivery_mode', models.CharField(default='standard', max_length=50)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagent')),
            ],
            options={
                'verbose_name': 'Delivery Request',
                'verbose_name_plural': 'Delivery Requests',
                'db_table': 'delivery_requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
