# Generated by Django 5.2 on 2025-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='product',
            name='approve_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
