# Generated by Django 5.2 on 2025-06-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_rejection_reason'),
        ('users', '0003_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Review Pending'), ('deleted', 'Deleted'), ('kept', 'Kept')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'product_reports',
            },
        ),
    ]
