mysql:
  image: mysql:8.0
  rootPassword: rootpass
  user: user
  password: userpass
  database: mydb
  storage: 1Gi

backend:
  image: ridma95/hand2hand:backend-latest
  port: 8000
  service:
    type: ClusterIP
    port: 8000
  superuser:
    name: admin
    password: password
  deeplApiKey: ebaef170-80f4-4787-a1fe-88363d94fb8c:fx
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

frontend:
  image: ridma95/hand2hand:frontend-latest
  port: 80
  service:
    type: ClusterIP
    port: 80
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  host: hand2hand.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
