mysql:
  image: mysql:8.0
  rootPassword: rootpass
  user: user
  password: userpass
  database: mydb
  storage: 1Gi

backend:
  image: ridma95/hand2hand:backend-latest
  port: 8000
  superuser:
    name: admin
    password: password
  deeplApiKey: ebaef170-80f4-4787-a1fe-88363d94fb8c:fx

frontend:
  image: ridma95/hand2hand:frontend-latest
  port: 80

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  port: 8080
